/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SketchesSketchIdRouteImport } from './routes/sketches.$sketchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SketchesSketchIdRoute = SketchesSketchIdRouteImport.update({
  id: '/sketches/$sketchId',
  path: '/sketches/$sketchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sketches/$sketchId': typeof SketchesSketchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sketches/$sketchId': typeof SketchesSketchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sketches/$sketchId': typeof SketchesSketchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sketches/$sketchId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sketches/$sketchId'
  id: '__root__' | '/' | '/sketches/$sketchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SketchesSketchIdRoute: typeof SketchesSketchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sketches/$sketchId': {
      id: '/sketches/$sketchId'
      path: '/sketches/$sketchId'
      fullPath: '/sketches/$sketchId'
      preLoaderRoute: typeof SketchesSketchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SketchesSketchIdRoute: SketchesSketchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
